### ISSUE TITLE
property-group is imported with scope of shared project but no way of a global scope

### ISSUE THREAD

**Issue by mdittbrenner215** [vmware/build-tools-for-vmware-aria#250]
### Description

property-group is imported with scope of shared project but no way of a global scope

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Preconditions:** [What are the preconditions to reproduce the issue]

**Expected behavior:** 
Have a way to import a global scope property group. 

**Actual behavior:** 
It imports only to the share project.
Worse part cant delete because its attached to a version blueprint which was released

**Reproduces how often:** 100%

**Component/s:** [What are the Build Tools for VMware Aria components affected by the issue (e.g. "common/artifact-manager", "maven/plugins/vra-ng", "typescript/vrotest", etc)]
vra-ng

```
propertyGroup.setProjectIdInRawData(this.projectId);
```
in VraNgPropertyGroupStore.java

**Affects Build/s:** [Which are the Build Tools for VMware Aria releases / builds affected by the issue]

#### Client

-   Build Tools for VMware Aria Version:
-   Visual Studio Code Version:
-   OS Version:

#### Server

-   vRealize Automation Version:
-   vRealize Orchestrator Version:
-   vRealize Operations Version:
-   vRealize Log Insight Version:

**Comment by SimonSparksUK** [comment]
This is currently affecting us

**Comment by mdittbrenner215** [comment]
Please remove the stale tag as it hasnt been looked at by VMware yet

**Comment by SimonSparksUK** [comment]
Nudge

**Comment by Michaelpalacce** [comment]
Can confirm this is a BUG. 

I believe pushing a property group without a projectId will make it global, as it works with other resources (needs to be verified).

Two places where logic needs to be changed in the VraNgPropertyGroupStore is:

- ![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/17056014/6b209ff8-b89e-489b-9cae-1c14c55b5e9a)
    - Here we need to modify this so we don't delete the projectId
- ![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/17056014/250aecf2-0e0d-42e9-bf98-997cbbd1d57b)
    - Here we need to set the projectId ONLY if it already exists as we do in other places
    
    
@SimonSparksUK Do you think you can create a quick PR and test this one out? Otherwise feel free to take a look at https://github.com/vmware/build-tools-for-vmware-aria/blob/main/SUPPORT.md#support

**Comment by VenelinBakalov** [comment]
Hi @mdittbrenner215 , I see in the code base that there is a definition for "global-property-group", could you check it that would help resolving the global scope topic at least?

**Comment by mdittbrenner215** [comment]
I know when we push content all of our content we use a projectid.  For example that gets used for import blueprints and cataloig items which i believe needs that projectid.

Since we have that in place it auto puts the projectid in for the property groups.
So in our case we would need to have a global property group but be able to import others.
