### ISSUE TITLE
Unable to Create a Project with Users assigned to the "Supervisor" role.

### ISSUE THREAD

**Issue by SimonSparksUK** [vmware/build-tools-for-vmware-aria#256]
### Description

Unable to Create a Project with Users assigned to the "Supervisor" role.

### Steps to Reproduce

    let objProjectsService:ProjectsService = new ProjectsService(this.objHttpClient);

    let objProjectSpecification:ProjectSpecification;
    objProjectSpecification.name = strProjectName;
    objProjectSpecification.description = strProjectName;
    objProjectSpecification.administrators = arrUserAdministrator;
    objProjectSpecification.members = arrUserMember;
    objProjectSpecification.viewers = arrUserViewer;
    objProjectSpecification.machineNamingTemplate = `t${strTenantID}`;
    objProjectSpecification.zoneAssignmentConfigurations = arrZoneAssignmentSpecification;
    objProjectSpecification.placementPolicy = "DEFAULT";
    objProjectSpecification.supervisor = arrUserSupervisor; **<== THIS IS THE MISSING PROPERTY!**

    let objCreateProjectParameters:CreateProjectParameters;
    objCreateProjectParameters.body_body = objProjectSpecification;

    let objCreateProjectHttpResponse:CreateProjectHttpResponse = objProjectsService.createProject(objCreateProjectParameters);

    if (objCreateProjectHttpResponse.status < 200 || objCreateProjectHttpResponse.status >= 300) {
      throw new Error(
        `Error while retrieving the Tenant for TenantID: ${this.strTenantID} from Auth Client in TenantService!`
      );
    }

    let objProject:Project = objCreateProjectHttpResponse.body;

**Preconditions:** 

NONE

**Expected behavior:** 

Creates a project with the users specified assigned to the supervisors role.

**Actual behavior:**

Code does not build using aria build tools.

**Reproduces how often:** 

100%

**Component/s:** 

com.vmware.pscoe.ts.vra.iaas/models/Project.d.ts/Project
com.vmware.pscoe.ts.vra.iaas/models/ProjectSpecification.d.ts/ProjectSpecification

Project
ProjectSpecification

**Affects Build/s:** 

ALL including latest 2.38.1

#### Client

-   Build Tools for VMware Aria Version:
-   Visual Studio Code Version:
-   OS Version:

#### Server

-   vRealize Automation Version: v8.16

### Additional Context

  
![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/10119404/a1543dd0-fe49-4eed-a5d8-2879a6990c50)

 
![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/10119404/171dbbef-c633-4985-aa2f-450cfd4e06c8)

**Comment by SimonSparksUK** [comment]
Nudge

**Comment by VenelinBakalov** [comment]
Hi Simon,

Thanks for raising your concern. Unfortunately, the issue you are describing is not related to Build Tools for Aria directly. This seems to be coming from interfaces/types defined in custom code (vRO package). While the package itself might be using Build Tools for Aria in order to transpile it (build the custom code into a vRO pakcage), the missing interfaces are coming from the code base of that package and not from Build Tools for VMware Aria. On first glance, I would assume that the package you are referring to has been created against an earlier version of vRA and the missing properties you are describing are most likely coming from a later version of vRA.

However, I can propose to you an easy alternative solution which you can implement in your own code base. You can use native TS inheritance to create your own interface that re-uses everything from that package's interfaces and add the missing property on top.

Here is an example of how this can work by defining your own type: "CustomProjectSpecification":

```typescript
export type CustomProjectSpecification = ProjectSpecification & {
    supervisors?: string[]
}
```
After that you can use your own defined CustomCloudAccountVsphereSpecification which preserves all of the original fields and adds the missing one on top and if needed at later point - you can continue to extend it.

I hope this helps to solve the issue.

P.s. In case the specification is interface and not a type you can use similar approach:
```typescript
export interface CustomProjectSpecification extends ProjectSpecification {
        supervisors?: string[]
}
```
