### ISSUE TITLE
Not able to create a cloud account with linked Mobility Cloud Accounts

### ISSUE THREAD

**Issue by SimonSparksUK** [vmware/build-tools-for-vmware-aria#267]
### Description

When creating a cloud account using TypeScript I want to be able to add the Site Associations

### Steps to Reproduce

This is the Aria Automation Cloud Account Edit View in the HTML5 UI.

![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/10119404/43f9fa16-3661-495a-adb6-07115cbdffce)

This is the Aria Automation REST API in Swagger showing the attribute which I would like to be able to set when creating a Cloud Account via TypeScript.

![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/10119404/f9e603e0-e799-4ac2-9dc2-7c2b13b98110)

This some sample TypeScript to show the missing attribute from the CloudAccountVsphereSpecification type.

![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/10119404/0d7e5698-9c3e-4bb5-ae9d-564219f8523b)

#### Client

-   Build Tools for VMware Aria Version: v2.38.1
-   Visual Studio Code Version: Latest
-   OS Version: Windows 11

#### Server

-   Aria Automation Version: v8.16
-   Aria Orchestrator Version: v8.16

### Additional Context

This is blocking our migration from vRA v7.6 to vRA v8.x we use it in multi-tenant mode.

**Comment by VenelinBakalov** [comment]
Hi Simon,

Thanks for raising your concern. Unfortunately, the issue you are describing is not related to Build Tools for Aria directly. This seems to be coming from interfaces/types defined in custom code (vRO package). While the package itself might be using Build Tools for Aria in order to transpile it (build the custom code into a vRO pakcage), the missing interfaces are coming from the code base of that package and not from Build Tools for VMware Aria. On first glance, I would assume that the package you are referring to has been created against an earlier version of vRA and the missing properties you are describing are most likely coming from a later version of vRA.

However, I can propose to you an easy alternative solution which you can implement in your own code base. You can use native TS inheritance to create your own interface that re-uses everything from that package's interfaces and add the missing property on top.

Here is an example of how this can work by defining your own type: "CustomCloudAccountVsphereSpecification":

```typescript
export type CustomCloudAccountVsphereSpecification = CloudAccountVsphereSpecification & {
    associatedMobilityCloudAccountIds?: string
}
```
After that you can use your own defined CustomCloudAccountVsphereSpecification which preserves all of the original fields and adds the missing one on top and if needed at later point - you can continue to extend it.

I hope this helps to solve the issue.

P.s. In case the specification is interface and not a type you can use similar approach:
```typescript
export interface CustomCloudAccountVsphereSpecification extends CloudAccountVsphereSpecification {
    associatedMobilityCloudAccountIds?: string
}
```
