### ISSUE TITLE
TagsService is Missing 3 Methods

### ISSUE THREAD

**Issue by SimonSparksUK** [vmware/build-tools-for-vmware-aria#270]
### Description

On Aria Automation v8.16 when browsing the swagger at the following URL

/iaas-api/swagger/webjars/swagger-ui/index.html#/Tags

there are 4 functions available as you can see in this screenshot

![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/10119404/e935781b-b57b-407a-bf3b-f0e9c1e856e7)

however in the typescript class there is only 1 function as you can see in this screenshot

![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/10119404/bee7fd7e-b23f-4c09-b490-0f019800df85)

Please create the 3 missing functions in the typescript class

**Comment by VenelinBakalov** [comment]
Hi Simon,

Thanks for raising your concern. Unfortunately, the issue you are describing is not related to Build Tools for Aria directly. This seems to be coming from interfaces/types defined in custom code (vRO package). While the package itself might be using Build Tools for Aria in order to transpile it (build the custom code into a vRO pakcage), the missing interfaces are coming from the code base of that package and not from Build Tools for VMware Aria. On first glance, I would assume that the package you are referring to has been created against an earlier version of vRA and the missing properties you are describing are most likely coming from a later version of vRA.

However, I can propose to you an easy alternative solution which you can implement in your own code base. You can use native TS inheritance to create your own class that extends and re-uses everything from that package's class and add the new functions on top.

Here is an example of how this can work by defining your own type: "CustomTagsService":

```typescript
export class CustomTagsService extends TagsService {
    constructor(httpClient: HttpClient) {
        super(httpClient);
    }

    public createTag(....) {.....};
    public deleteTag(....) {.....};
}
```
After that you can use your own defined CustomCloudAccountVsphereSpecification which preserves all of the original fields and adds the missing one on top and if needed at later point - you can continue to extend it.

I hope this helps to solve the issue.

P.s. In case the specification is interface and not a type you can use similar approach:
```typescript
export interface CustomCloudAccountVsphereSpecification extends CloudAccountVsphereSpecification {
    associatedMobilityCloudAccountIds?: string
}
```
