### ISSUE TITLE
Run unit tests each in their own runtime

### ISSUE THREAD

**Issue by pe1pip** [vmware/build-tools-for-vmware-aria#355]
### Description

Each unit test file in a package should be able to depend on the environment being clean. That is, 'top level' describe sections in separate test files should not influence each other in any way. making sure that one test doesn't pollute the environment of the next is at times very hard or even impossible.

### Alternatives

I see none

**Comment by Michaelpalacce** [comment]
Hey @pe1pip is that a practice you've seen somewhere? Never heard of this before.

Keeping your unit tests' global scope clean is somethingt hat you should take care of yourself. Usually `jasmine` has a randomizer which I am not 100% certain is in place, that randomizes the order of execution which should give you an indication if a test depends on another. Can we get more information?

**Comment by pe1pip** [comment]
Hi,

I recall that when testing javascript each test file has it's own java runtime, we run into this issue when testing typescript that it looks like all test files are concatenated into a single runtime.

For mocking we do things like so:

```ts
import SomeClass from '../actions/someClass'
import SomeClassMock from '../helpers/someClassMock.helper'
import DutClass from '../actions/dutClass'

describe('something', () => {
  const saveSomeClass = SomeClass

  let someClassSpy: jasmine.SpyObj<SomeClass>
  let dut: DutClass

  beforeEach(() => {
    (SomeClass as any) = SomeClassMock
    someClassSpy =  spyOnAllFunctions(SomeClass.prototype)
    dut = new DutClass()
  })
  afterEach(() => {
    (SomeClass as any) = saveSomeClass
  })
  it('something', () => {
    expect(dut.method()).toEqual(something)
  })
})
```

This works fine most of the time, but sometimes SomeClass doesn't get restored to the original class, however hard we try, especially when SomeClass is an abstract class and DutClass extends SomeClass. Because we do all sorts on initialisation of for example RESTHost and RestHostManager in the constructor of the classes that we don't want to do during unit testing, we really need to make sure that the constructor of in this example `SomeClass` is never called.

The biggest problems arise when SomeClass en DutClass are in the same package and we want to start performing unit tests on SomeClass.

**Comment by Michaelpalacce** [comment]
I just want to start with the fact that there are some fundamental issues with these tests. If you are testing `DutClass` and you need to do such a mocking on `SomeClass` and not to mention that `SomeClass` seems to be a major problem then:

1. `DutClass` needs to inject `SomeClass`'s instances instead of relying on some super global singleton getInstance or whatever
2. `SomeClass` is too complex to be mocked it seems like, take a look at "Humble Object Pattern"
3. Tests that modify the `prototype` of a class usually lead to side effects and are a flag that something needs to be improved.

Regarding: 

> I recall that when testing javascript each test file has it's own java runtime, we run into this issue when testing typescript that it looks like all test files are concatenated into a single runtime.

I don't belive that is how things works. Java has nothing to do with the Runtime of the tests. Java is used to build the testbed, then run a javascript process to execute the tests (jasmine)

Can you give me a minimum reproducible example that I can run and this happens and I'd gladly take a look ?
