### ISSUE TITLE
The `determineRuntime` in `polyglotpkg` should not try to determine and change the runtime

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#391]
### Description

There is code currently that checks if the user supplied something like: "node:12" in an abx action to translate that to "nodejs". This is a responsibility of the user. vRO and ABX actions are different in that regard and that is ok.

**Comment by VenelinBakalov** [comment]
With 3.0.0 we need to remove the wrongly defined aria sample as well: https://github.com/vmware-samples/build-tools-for-vmware-aria-samples/blob/main/polyglot-all/src/polyglotallnodejs/polyglot.json
At the time of creation it was properly defined since the initial versions only supported nodejs as runtime but that changed later on.

**Comment by VenelinBakalov** [comment]
Related commit:
https://github.com/vmware/build-tools-for-vmware-aria/pull/392/commits/50da667f02569e543b87c10af3d503848644dd1b

**Comment by VenelinBakalov** [comment]
Related code change:
https://github.com/vmware/build-tools-for-vmware-aria/blob/main/typescript/polyglotpkg/src/lib/utils.ts#L37-L78

**Comment by pe1pip** [comment]
there are more issues in the polyglot package that we might want to address:
 - powerCLI version is lagging behind, keeping the versions definitions in `typescript/polyglotpkg/src/lib/model.ts` up to date is maybe not ideal
 - we have defined our own runtime environment for PowerCLI, because we apparently need some additional modules, so even if the runtime list is up to date our PowerCLI scripts can't be managed by the BT:

![Screenshot 2024-09-26 at 14 01 21](https://github.com/user-attachments/assets/af7e0028-ab0e-43fa-ab5b-368005bb3782)

**Comment by Michaelpalacce** [comment]
@pe1pip Valid comment, but this is not the place for this, open an issue if one does not exist.
