### ISSUE TITLE
Add functionality to pull Custom Name Templates from vRA

### ISSUE THREAD

**Issue by GeorgiAStoev** [vmware/build-tools-for-vmware-aria#423]
### Description

I want to be able to pull Custom Name Templates from vRA using VRBT. Currently, this is a prerequisite for projects.

![image](https://github.com/user-attachments/assets/819aa5dd-44c0-4fc7-be57-31b1ab49bfbd)

**Comment by VenelinBakalov** [comment]
Decided on roadmap meeting 03/10/24 that this feature will not be implemented
* Most Assembly -> Infrastructure components are not suitable to be managed by Build Tools for Aria project
* It is a one time configuration
* Project mapping will be difficult considering as well that by design we push content to 1 specific project - the one defined in settings.xml
* Re-pushing the same Custom Name when it is already in use can lead to issues related to counters and conflicts during VM deployment which will not be automatically solved by Aria Automation

**Comment by VenelinBakalov** [comment]
Just for future reference, some `push` strategies for project target which we discussed with @Michaelpalacce 
* Whatever project name is pulled from an environment needs to exist in the push target environment, otherwise an error is thrown
* Array of names, whichever project on the target environment matches any of the name we assign the template to it, for the ones that are missing we just log warning
* Ignore projects defined in the custom name template that was pulled from source environment and in the push target environment assign only to the project defined in `settings.xml`
