### ISSUE TITLE
Add policies to the content.yaml

### ISSUE THREAD

**Issue by RV1959** [vmware/build-tools-for-vmware-aria#77]
### Description

Currently, VBT does not support policies in the content.yaml
As a result, we now need to manually copy some organisation-wide Day-2-Actions policies from Development vRA to Acceptance and to Production. The large number of actions makes this an error-prone operation that should be automated.

It would be great if VBT was able to import/export these and other policies.
On export, the organisation-id should be taken from the settings.xml of course.

### Alternatives

n/a

### Additional Context

n/a

**Comment by Michaelpalacce** [comment]
Hey @RV1959,

Regarding content sharing policies? https://github.com/vmware/build-tools-for-vmware-aria/releases/tag/v2.31.0

They are supported as of 2.31.0.

Read more about them at:

https://github.com/vmware/build-tools-for-vmware-aria/blob/v2.31.0/docs/versions/v2.31.0/Release.md

Are you talking about other policies?

**Comment by Michaelpalacce** [comment]
Closing this for now, feel free to re-open if needed.

**Comment by htourneu** [comment]
Hello @Michaelpalacce ,

From the description, @RV1959 mentions day-2 action policies.
Looking further into vRA-NG it seems indeed this is not currently supported, is that right?

Best regards,

**Comment by imihov1988** [comment]
There is a discussion to be held around adding the new types of policies.

The Content Sharing Policy is defined like a single policy (the **VraNgContentSharingPolicyStore**). However in Aria there are 6 types of policies - like Approval, Day 2 etc

One possible solution is to refactor the VraNgContentSharingPolicyStore, extract the common policy logic in a parent abstract **VraNgPolicyStore** store and make the VraNgContentSharingPolicyStore one of its 6 derived classes. However there will be changes needed above because currently there is only one ContentType for policies - policy.

Another option is to rename the **VraNgContentSharingPolicyStore** to a **VraNgPolicyStore** without making it a base abstract class and to make it handle internally with different strategies the implementations of the different policies processings. However this seems to me will not align with the current model of architecture.

**Comment by RV1959** [comment]
I'd say we should keep close to the model vRA itself uses, that would mean
**_extract the common policy logic in a parent abstract VraNgPolicyStore store and make the VraNgContentSharingPolicyStore one of its 6 derived classes_**

**Comment by joroaf** [comment]
We need to support all types of Aria Policies:
Policy Types
  * Content Sharing Policy
  * Resource Quota Policy
  * Lease Policy
  * Day 2 Actions Policy
  * Approval Policy
  * Deployment Limit Policy

**Comment by imihov1988** [comment]
@joroaf It seems I will get off-projects time next week so I started working today again on this task.
I'm planning now the implementation of the other policy types, or at least the Day 2 Actions Policy as a start.
But I see not all data from the Content Sharing is represented in the Build Tools project **VraNgContentSharingPolicy** class, for example the list of items for content sharing.

I'd also like to know from where the string of 'policy' comes indicating the **PackageContent.ContentType**-s, I guess from Aria API, just for some reason I didnt find it in the docs.

Would you have a possibility for a 15-20 min sync meeting on Monday just to exchange some knowledge about the domain of the desired functionality?

**Comment by VenelinBakalov** [comment]
@Michaelpalacce @joroaf this issue is going to be closed with those 2 PRs right?
https://github.com/vmware/build-tools-for-vmware-aria/pull/202
https://github.com/vmware-samples/build-tools-for-vmware-aria-samples/pull/1

Or there are further extensions to the policies required? I want to create a link between the issue and the PR

**Comment by htourneu** [comment]
@VenelinBakalov - both PR you quoted are about vRo policies, this issue is related to vRa Service Broker policies, ie: day 2 action policies, content sharing, approvals, quota etc...

**Comment by VenelinBakalov** [comment]
@Michaelpalacce this is still active right? if yes, no need to respond, just adding this comment to remove stale

**Comment by VenelinBakalov** [comment]
Closed with https://github.com/vmware/build-tools-for-vmware-aria/pull/242 and to be included in next release
